lpc-rs/lpc8xx-hal

- src/lib.rs
This re-exports relevant type from the lpc82x crate. Users of this crate
should not need to depend on lpc82x directly.
Close #17
> Re-export anything relevant from lpc82x

- src/gpio.rs
- src/lib.rs
- src/pmu.rs
- src/sleep.rs
- src/swm.rs
- src/syscon.rs
- src/usart.rs
- src/wkt.rs
Simplifies the API by removing `System`, `Clocks`, and `Resources`, only leaving `Peripherals`. Types that were previously accessible from `Clocks` and `Resources` have been moved into their respective peripheral modules. `syscon` and `pmu` have been reorganized to accomodate that.
Also renames all peripheral types to more closely follow the language used in the user manual. See #18 for a discussion of the issue.
> Reorganize API structure

- src/syscon.rs
- src/usart.rs
Makes the API for controlling UART baud rates safe by making it impossible to change a baud rate once it is being used for a USART peripheral. Closes #7 because the safety aspects mentioned there have been addressed. A follow-up issue will be opened for the convenience aspects that haven't been addressed by this pull request.
> Improve baud rate API

- src/gpio.rs
- src/lib.rs
- src/swm.rs
- src/usart.rs
This pull request lays more groundwork for issue #2, a completely safe pin API, by reorganizing the SWM API.
I originally thought that adding type state to pin types would be enough to create a pin API that is safe at compile-time. Turns out I was wrong, as the switch matrix API is much more nuanced and powerful than I was aware of, and allows assigning multiple functions to the same pin.
I believe this can be modelled by also adding type state to each fixed or movable function. This requires each function to be represented by its own type, which is what this pull request does.
> Lay groundwork for SWM API safety improvements

- src/gpio.rs
- src/lib.rs
- src/swm.rs
- src/usart.rs
This pull request updates the pin API, making it safer to use by adding type state for GPIO, as well as laying groundwork for additional SWM-related safety improvements later.
This is another step towards fixing #2, but we're not quite there yet.
> Update pin API

- src/gpio.rs
- src/lib.rs
- src/pmu.rs
- src/sleep.rs
- src/swm.rs
- src/syscon.rs
- src/usart.rs
- src/wkt.rs
Some peripherals consist of multiple types, one of which is the "main" type. So far, I've used various names for those, but I've decided on one now: `Handle`, as this main type can be seen as a handle to the peripheral where such a thing is required.
> Update peripheral type names

- src/sleep.rs
The sleep function was triggering the WKT interrupt handler, which it
really shouldn't do. This mistake snuck in while I squashed some commits
in #61.
> Fix sleep function triggering WKT handler

- src/lib.rs
This is a partial fix for #71. This pulll request fixes the problem as far as this crate is concerned, but when building with the `rt` feature, the lpc82x crate won't build for the same reason.
> Fix build on latest nightly

- examples/gpio.rs
- examples/usart.rs
- src/gpio.rs
- src/lib.rs
- src/pmu.rs
- src/sleep.rs
- src/swm.rs
- src/usart.rs
- src/wkt.rs
Changes the peripheral APIs to take ownership of peripheral structs. The only exception to this is SYSCON, as the svd2rust-generated code doesn't allow us to take ownership of single registers, which is what SYSCON (in its current form) would require.
> Take ownership of peripheral structs

- examples/gpio.rs
- src/gpio.rs
- src/lib.rs
- src/swm.rs
- src/usart.rs
This is a huge step towards reaching the goals laid out in #76. There's only one struct and one trait for SWM functions now. Many of the SWM-related methods in the pin API have been removed.
> Merge infrastructure for fixed and movable functions

- examples/gpio.rs
- examples/usart.rs
- src/gpio.rs
- src/lib.rs
- src/pmu.rs
- src/sleep.rs
- src/swm.rs
- src/syscon.rs
- src/usart.rs
- src/wkt.rs
Radically simplifies state management, both internally and from an API perspective, by controlling the initialization of all peripherals, thereby making sure that the user couldn't have changed any peripherals (in safe code) before the API was initialized.
Close #69
> Simplify state management

- .travis.yml
- Cargo.toml
- src/swm.rs
- tests/compile-fail/swm/assign-function-to-multiple-pins.rs
- tests/compile-fail/swm/assign-multiple-output-functions.rs
- tests/compile-fail/swm/unassign-function-from-wrong-pin.rs
- tests/compile-fail/swm/unassign-unassigned-input-function.rs
- tests/compile-fail/swm/unassign-unassigned-output-function.rs
- tests/compiletest.rs
Also includes a few basic tests.
> Add compiletest infrastructure

- lpc82x-hal/Cargo.toml
Based on #152, so shouldn't be merged before that one has been merged.
> Remove maintanance badge

- lpc82x-hal/src/lib.rs
- lpc845-hal/Cargo.toml
- lpc845-hal/examples/gpio.rs
- lpc845-hal/src/lib.rs
- lpc8xx-hal-common/src/gpio.rs
- lpc8xx-hal-common/src/lib.rs
- lpc8xx-hal-common/src/reg_proxy.rs
- lpc8xx-hal-common/src/swm.rs
- lpc8xx-hal-common/src/syscon.rs
- Add compatibility layer for differently named peripherals `raw_compat` (Unfortunately couldn't find a way to do the same for registers)
- Add pin assignments for for lpc845
- Currently a few are commented out, as gpio1 & pinenable1 are currently missing 
- There's now also a Dac & capacitive measurement, I think the best way to handle them is to rename `pin_state::Adc` to `pin_state::Analog`.
- Disable UARTFRG & IRC for lpc845, as they don't exist
- Add `Peripherals` to lpc845. As the gpio is per default disabled, this also meant adding an additional `new` constructor(?) for disabled gpio peripherals and renaming the old one to `new_enabled`.
- Add a gpio example. Currently without accurate timing, as that isn't ported yet
As an aside: What's your policy about rom routines, as the fro …
> Add gpio functionaliy to lpc845

- Cargo.toml
- examples/845_gpio.rs
- openocd_lpc845.cfg
- openocd_lpc845.gdb
- scripts/build.sh
This:
- (Re-)adds the lpc845 gpio example
- Add correct openocd config
TODO:
`rt` feature doesn't work. Both pac crates seem to added as dependencies, with the lpc82x-pac `device.x` being used on my machine, regardless of the selected mcu. This results in linker failure. 
The simplest fix appears to be adding two separate `rt` features, but that might result in user confusion
> LPC845 fixup

- Cargo.toml
- examples/gpio_delay.rs
- src/delay.rs
- src/lib.rs
This is based on https://github.com/stm32-rs/stm32f0xx-hal/blob/master/src/delay.rs, (mostly) written by myself and adjusted to better fit the api.
Also adds a gpio example based on this that's less hacky for the lpc845.
I didn't find a way to get the current system frequency & (for example) i2c seems to rely on it being 12 MHz, so it's just hardcoded for now.
> Add delay implementation based on systick

- Cargo.toml
Otherwise debugging in release mode doesn't provide the corresponding source code in gdb.
Also optimizes more, so that the release build is as small as possible
> Add debug information to release builds & more optimization

- Cargo.toml
- examples/gpio_sleep.rs
- src/lib.rs
- src/syscon.rs
- src/wkt.rs
FroDerivedClock is the only thing different, but it's the same as IrcDerivedClock with a different name (no idea why nxp did that).
> Enable WKT for lpc845

- src/lib.rs
This is a bit messy, but I think it's better than the duplicated code we
had before. It's also going to get less messy over time, as more
peripheral APIs are implemented for LPC845.
This changes a few field names on the LPC82x side.
> Merge `Peripherals` into one struct

- Cargo.toml
- src/wkt.rs
Blocked until next version is release. See https://github.com/lpc-rs/lpc-pac/pull/45.
> Upgrade to latest `lpc845-pac` release

- build.rs
Turns out the previous approach only worked when the build.rs was
executed in the HAL repository.
> Make build.rs work for dependencies

- src/swm.rs
These are very minor things, but I thought I'd create a PR since I was already skimming the docs.
> Fix some typos in SWM documentation

- build.rs
I ran into this when starting a new project depending on LPC8xx HAL.
Seems pretty serious, since this might be the first point of contact
with this library for many users.
> Fix panic in build script, if target doesn't exist

- examples/gpio_sleep.rs
- examples/i2c_vl53l0x.rs
- examples/pmu.rs
- examples/usart.rs
- rustfmt.toml
- src/delay.rs
- src/dma.rs
- src/gpio.rs
- src/i2c.rs
- src/lib.rs
- src/pmu.rs
- src/sleep.rs
- src/swm.rs
- src/syscon.rs
- src/syscon/clocksource_82x.rs
- src/syscon/clocksource_845.rs
- src/usart.rs
- src/wkt.rs
Before we introduced `cargo fmt`, I kept my line widths to 80, but the default for `cargo fmt` is 100. I guess which one is better is mostly subjective, but given the size of my screen, the way I divide it between different applications, and my preferred font size, 100 is just too long :-)
So yeah, I prefer this setting. Please let me know what you think.
> Set maximum line width to 80

- build.rs
It occured to me, that the previous error message is highly misleading
for the regular use case (adding LPC8xx HAL as a dependency).
> Improve error message in `build.rs`

- examples/usart.rs
- src/lib.rs
- src/swm.rs
Also makes the `new` functions public, to stay in line with gpio and
bypass unused function warnings.
Was there a good reason to implement these on `Handle` instead of the whole peripheral?
> Force swm to be enabled on lpc845, fix #183

- examples/usart.rs
- src/syscon/frg.rs
This makes the API much friendlier, as it no longer requires the user to
import an obscure type from the PAC.
> Re-export clock source enum from `frg` module

- build.rs
I've seen `lpc8xx-hal` being rebuild every time I rebuild my project.
This seems to have been caused by incorrect instructions being given to
Cargo, about when the build script should be re-run.
> Fix `build.rs` being re-run on every build

- src/gpio.rs
- src/i2c.rs
- src/lib.rs
- src/pmu.rs
- src/swm.rs
- src/syscon.rs
- src/usart.rs
- src/wkt.rs
- Fix broken links
- Replace references to lpc82x-hal with lpc8xx-hal
This didn't fix any doc examples
> Fix out of date documentation

- examples/gpio_timer.rs
- src/lib.rs
- src/mrt.rs
- src/mrtimer.rs
TODO:
- Check what's up on the lpc82x
The UM says it's a 31 bit timer, but the documentation for MODCFG.NOB suggests 24 bits
@hannobraun Could you check? I unfortunately don't have an lpc82x device
> Implement MRT abstraction

- Cargo.toml
- examples/adc.rs
- examples/ctimer_fade.rs
- examples/gpio_delay.rs
- examples/i2c_eeprom.rs
- examples/pmu.rs
- examples/rtfm.rs
- src/lib.rs
The point of this is to improve interoperability with RTFM. Interoperability is still not very good (due to the lifetimes requires all over the API), but it's a start.
> Remove core peripherals from `Peripherals`

- Cargo.toml
- build.rs
It doesn't build on Windows, which I think is enough reason to make it
optional and unselected by default.
I don't think having it as an optional dependency is particularly
useful, but I didn't want to remove it outright. I'm hoping that
Termion's problems on Windows are temporary, and once it is fixed,
restoring the previous functionality will be easy.
Close #212
> Make dependency on Termion optional

- examples/adc.rs
- examples/ctimer_fade.rs
- examples/gpio_delay.rs
- examples/gpio_input.rs
- examples/gpio_simple.rs
- examples/gpio_sleep.rs
- examples/gpio_timer.rs
- examples/i2c_eeprom.rs
- examples/i2c_vl53l0x.rs
- examples/pmu.rs
- examples/rtfm.rs
- examples/spi_apa102.rs
- examples/usart.rs
- scripts/build.sh
- src/ctimer.rs
- src/gpio.rs
- src/lib.rs
- src/pins.rs
- src/spi.rs
- src/swm.rs
- src/usart.rs
This doesn't leave the API in a perfect state, but it's a clear improvement. I'm planning some more improvements to improve RTFM compatibility, and maybe I'll move more stuff around while I'm doing that.
> Move pin API to dedicated module

- examples/gpio_delay.rs
- examples/gpio_input.rs
- examples/gpio_simple.rs
- examples/gpio_sleep.rs
- examples/gpio_timer.rs
- examples/rtfm.rs
- src/gpio.rs
- src/pins.rs
- src/swm.rs
This is another milestone in my ongoing effort to update the pins/GPIO API. It's based on #216, and I suggest reviewing/merging that one first.
> Clean up and simplify GPIO API

- src/usart.rs
> Remove `RegProxy` from USART; remove trait bound on USART structs

- src/pinint.rs
This is required for some use cases, but had been forgotten initially.
> Re-export `Trait` from `pinint`

- src/gpio.rs
- src/lib.rs
- src/pins.rs
- src/pins/gen.rs
- src/pins/pin.rs
- src/pins/state.rs
- src/swm.rs
- src/swm/fixed_functions.rs
- src/swm/functions.rs
- src/swm/handle.rs
- src/swm/movable_functions.rs
- src/swm/peripheral.rs
- src/swm/state.rs
- src/usart.rs
- src/usart/peripheral.rs
- src/usart/rx.rs
- src/usart/tx.rs
Also contains a non-documentation fix that didn't seem substantial enough to put in its own PR.
@david-sawatzke I'd like to re-iterate my opinion that we should add the core API for each type as inherent methods, and only provide the `embedded-hal` traits in addition. Please take a look at the documentation of `USART`, `usart::Rx`, `usart::Tx`, and `GpioPin`.
It's totally not obvious what kind of API they provide. The relevant trait implementations are hidden in a list of stuff that is irrelevant to the user. Even if you know what you're looking for, you have to click on a `[+]` _twice_, before a method signature shows up.
I've worked around this by adding links to the relevant traits to the documentation of each of those structs, but those links now have to be maintained and will soon be …
> Update some documentation

- src/adc.rs
- src/ctimer.rs
- src/delay.rs
- src/gpio.rs
- src/i2c.rs
- src/mrt.rs
- src/spi.rs
- src/usart/peripheral.rs
- src/usart/rx.rs
- src/usart/tx.rs
- src/wkt.rs
Also removes an outdated note about possible i2c limitations
(based on https://github.com/lpc-rs/lpc8xx-hal/pull/233#issuecomment-611881482)
Notes:
- Ignored marker traits (like `Periodic` & `Channel`)
- Left out trait descriptions when it didn't make sense
> Improve documentation (embedded-hal traits)

- src/i2c.rs
- src/i2c/clock.rs
- src/i2c/peripheral.rs
- src/spi.rs
- src/spi/clock.rs
- src/spi/peripheral.rs
- src/syscon/clock_source.rs
- src/syscon/clock_source/clocksource_82x.rs
- src/syscon/clock_source/clocksource_845.rs
- src/usart.rs
- src/usart/clock.rs
- src/usart/peripheral.rs
Details in the commits. This enables some further clean-ups in the I2C and SPI clock source code.
> Clean up clock source code

- examples/i2c_eeprom.rs
- examples/i2c_vl53l0x.rs
- src/i2c.rs
- src/i2c/error.rs
- src/i2c/peripheral.rs
I'm currently working on I2C slave mode. Since that might still take a bit more time (it's currently not working) and since it looks like I might be adding more error handling code on the master side to debug it, I figured I'd submit this now, to at least get some of it reviewed, and to keep any merging and rebasing on my side to a minimum.
> Prepare I2C module for adding slave mode

- Cargo.toml
- examples/pinint.rs
- examples/rtfm.rs
The RTFM framework has been renamed to RTIC. Everything else should be
the same, so this change should basically be a no-op.
> Migrate from RTFM to RTIC

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
It's been a while since we published the last release, and I think the next one is overdue. As indicated by the changelog, it's easily going to be our biggest release yet. The reason I want to get it out right now, is because of the aforementioned article I'm writing. I don't want to depend on an outdated version, and I also don't want to use a GitHub dependency, if I can avoid it.
@david-sawatzke: Please let me know what you think. Don't merge this yet, as I still have to do a bunch of steps once you've approved this:
> Release version 0.7.0

- src/gpio.rs
This is a pretty bad bug. I suggest we publish a patch release after merging this.
> Fix `embedded-hal` version of `set_low`

- examples/pinint.rs
- src/gpio.rs
This continues the work done in #242.
This is based on #246. Until that's merged, I'm leaving this as a draft.
> Add more infallible GPIO methods

- CHANGELOG.md
- Cargo.toml
I've decided to also include #247 in this release. I figured it doesn't matter much one way or the other, but not including it would have meant I might have missed it in the changelog for the next release, as GitHub orders merged PRs by date opened, not date merged.
What needs to be done now:
- @david-sawatzke:
- @hannobraun:
> Release version 0.7.1

- Cargo.toml
It has been broken for the 0.7.x releases. This should do it.
> Fix docs.rs build

- Cargo.toml
- Embed.toml
- README.md
- examples/adc.rs
- examples/ctimer_fade.rs
- examples/gpio_delay.rs
- examples/gpio_input.rs
- examples/gpio_simple.rs
- examples/gpio_sleep.rs
- examples/gpio_timer.rs
- examples/i2c_eeprom.rs
- examples/i2c_vl53l0x.rs
- examples/pinint.rs
- examples/pmu.rs
- examples/rtfm.rs
- examples/spi_apa102.rs
- examples/usart.rs
I've left the OpenOCD configuration in the repository, as cargo-embed isn't a full replacement yet (GDB server doesn't seem to be fully-featured). But I think this configuration is a better default, especially with probe-rs's pace of development.
> Add configuration for cargo-embed; switch examples to use `panic-rtt-target`

- src/i2c.rs
- src/i2c/error.rs
- src/i2c/master.rs
- src/i2c/peripheral.rs
I've been having massive problems getting I2C slave mode to work. In the end it turned out my problems were hardware-related, but these are some software improvements that came out of the whole ordeal.
> Improve robustness of I2C code

- examples/usart_dma.rs
- src/dma.rs
- src/dma/buffer.rs
- src/dma/channels.rs
- src/dma/transfer.rs
- src/lib.rs
- src/usart/instances.rs
- src/usart/peripheral.rs
- src/usart/rx.rs
- src/usart/tx.rs
Based on #260. I recommend reviewing/merging that one first.
Close #124.
> Add support for DMA-based reading from USART

- examples/usart_dma.rs
- src/dma.rs
- src/dma/channels.rs
- src/dma/descriptors.rs
- src/dma/gen.rs
- src/dma/peripheral.rs
- src/dma/transfer.rs
- src/lib.rs
- src/usart/instances.rs
- src/usart/rx.rs
- src/usart/tx.rs
This PR contains multiple orthogonal clean-ups, the most significant of which removes the lifetime from `Channel` and `Transfer`, making the API much more convenient to use in non-trivial use cases.
> Clean up DMA module

- Cargo.toml
- examples/i2c_master_slave_dma.rs
- src/dma/buffer.rs
- src/dma/transfer.rs
- src/i2c/instances.rs
- src/i2c/master.rs
- src/usart/rx.rs
- src/usart/tx.rs
Based on #263. I recommend reviewing/merging that one first.
> Add DMA support for I2C master mode

- examples/adc.rs
- examples/i2c_eeprom.rs
- examples/i2c_vl53l0x.rs
- examples/pmu.rs
- examples/usart.rs
- examples/usart_dma.rs
- src/usart.rs
- src/usart/peripheral.rs
- src/usart/rx.rs
- src/usart/settings.rs
- src/usart/state.rs
- src/usart/tx.rs
This is mostly restricted to settings that don't require new modes (like synchronous or RS-485 mode) to be added.
> Add support for changing USART settings

- src/dma.rs
- src/dma/buffer.rs
- src/spi.rs
- src/spi/dma.rs
- src/spi/instances.rs
- src/spi/peripheral.rs
- src/usart/instances.rs
This pull request is based on #263 and #264. I recommend reviewing/merging those first.
> Add DMA support for SPI master mode

- src/usart/flags.rs
I'm not sure how this slipped through my test suite[1], bit it did. I
think ideally (and I've mentioned this before), the flags infrastructure
would be independent of a specific peripheral, and would be used by all
peripherals to manage their flags. Once that is the case, we should find
a way to write some unit tests, but at this moment, I'm not sure exactly
how to do that.
[1] https://github.com/braun-embedded/lpc845-test-stand
> Fix bitwise operator when checking flag

- examples/i2c_master_slave.rs
- examples/i2c_master_slave_dma.rs
- src/i2c/error.rs
- src/i2c/master.rs
- src/i2c/peripheral.rs
- src/i2c/slave.rs
- src/reg_proxy.rs
Follow-up to #282 by @jacobbramley. Turns out we missed one place that had to be modified.
> Fix handling of I2C slave address

- .vscode/settings.json
- Cargo.toml
- src/delay.rs
- src/gpio.rs
- src/lib.rs
I've decided to start with the traits that I need right now (GPIO and delay), rather than trying to do everything, which I neither have the time to do nor to test. I figure we can extend support as needed.
Contains some other random commits in addition to the embedded-hal stuff. Those were things I happened upon while working on this, and I figure they're minor enough to not need their own pull request.
> Add partial support for embedded-hal 1.0.0-alpha.1

- Cargo.toml
It has recently come to my attention that Cargo treats different alpha
versions as semver-compatible. This is bad, as those could contain
breaking changes, and a simple `cargo update` by a user of LPC8xx HAL
could break their build.
Pinning to one specific alpha version should fix that particular
problem.
> Update and pin embedded-hal alpha version

- Cargo.toml
- examples/gpio_dynamic.rs
- src/gpio.rs
- src/mrt.rs
- src/pins/mod.rs
- src/pins/pin.rs
This PR adds a `DynamicPin which can change direction at runtime. I've also taken the liberty to refactor some duplicate code into helpers.
Also adds an example that demonstrates how to use these.
The current limitation is that the pin id is still baked into a DynamicPin's type, which makes it difficult to e.g. pass a bunch of these around in a collection to pick and reconfigure them at runtime. I'm working on a solution for this that's probably a breaking change to this PR, but am only ~halfway there.
> Add DynamicPin

- src/mrt.rs
As discussed in https://github.com/braun-embedded/embedded-test-stand/issues/108 .
I didn't make any changes to `Channel::value` and `Channel::reload_value` because to me it seemed like they delivered the right type in the situations they were used in, maybe that's a discussion for 2021 :)
> mrt-Ticks: add conversion to u32

- scripts/build.sh
- scripts/test.sh
- test-suite/.cargo/config.toml
- test-suite/Cargo.toml
- test-suite/README.md
- test-suite/src/lib.rs
- test-suite/tests/Cargo.toml
- test-suite/tests/tests/test.rs
I'd like to easily run tests on all target platforms after making a change, instead of having to manually run examples with different command-line arguments for each target. This pull request adds testing infrastructure based on defmt-test. The test suite only contains some dummy tests right now, to verify that the infrastructure works.
I plan on adding real tests with some changes I'm working on, but I wanted to submit this separately, in case there's anything that needs to be discussed here.
> Add test suite using defmt-test

- Cargo.toml
- examples/gpio_generic.rs
- examples/pinint.rs
- src/gpio.rs
- src/pinint/interrupt.rs
- src/pins/gen.rs
- src/pins/mod.rs
- src/pins/pin.rs
- src/pins/traits.rs
- src/swm/movable_functions.rs
Hi everyone,
the goal of this PR is more to start a discussion rather than getting it merged as-is (as you can see, there's quite a lot of Doc TODOs in there anyway).
The code in this PR... works (I've been using it [in my test-stand fork](https://github.com/Lotterleben/lpc845-test-stand/tree/generic_dynamic_pin) ; beware– there's a lot of code in dire need of cleanup in there), but I'm not convinced it is the best solution.
The problem it tries to solve is:
Currently, Pin IDs are baked into each pin type. This limits the applicability of Dynamic GPIO Pins: While I can define pins to be changeable at runtime (for example in a Test stand context to re-configure the LPC from test case to test case), I can't gather them in a vector, or define functions like `fn initialize_pin(pin: …
> RFC: more generic Dynamic Pins

- src/gpio.rs
- src/pins/gen.rs
- src/pins/pin.rs
- src/pins/traits.rs
as promised, resize `pins::Trait` to `u8`
Based on https://github.com/lpc-rs/lpc8xx-hal/pull/305 ; so:
- ~relevant commit is the second one: https://github.com/lpc-rs/lpc8xx-hal/commit/8d91838fa454241790c546756866c07f5332b157~
- ~should be rebased & only merged after #305 is merged~
> `pins::Trait`: downsize to `u8`

- src/usart/peripheral.rs
- src/usart/rx.rs
I've verified that receiving characters via USART still works with this code. But I don't have a setup that would allow me to inject errors, so I can't test whether this has the intended effect. All feedback is appreciated!
Close #307
> Improve USART error handling

- Cargo.toml
- examples/i2c_master_slave.rs
- examples/i2c_master_slave_dma.rs
- examples/pinint.rs
- examples/rtic.rs
The build was broken due to the release of the new RTIC alpha version.
We pin a specific RTIC version in Cargo.toml to prevent just that, but
that won't prevent Cargo from happily picking up breaking changes from
transitive dependencies. Since RTIC consists of multiple crates, that is
what happened here.
We could explicitly specify and pin all those transitive dependencies in
Cargo.toml to prevent that from happening, but that would get unwieldy.
I decided that it's probably best to just upgrade to the latest alpha,
ride it out for this alpha cycle, and be more careful about adding alpha
dependencies in the future.
> Upgrade to latest RTIC alpha

- src/gpio.rs
Hi 👋,
I've found myself creating match statements like these
```
let pinint0_level = match pinint0_pin.is_high() {
true => pin::Level::High,
false => pin::Level::Low,
};
```
more often than I'd like, and imo it'd be neat to resolve this at the HAL level.
So this PR adds a native `get_level()` (or `get_set_level()` in the case of `Output` pins) function to make the level directly accessible.
> gpio.rs: add get_level()

- Cargo.toml
We aren't affected by the breaking changes of the 0.7 release. The PAC
has already been updated to accept both 0.6 and 0.7, so this leaves it
up to the user which version to use.
> Update dependency on cortex-m-rt

- Cargo.toml
This also relaxes the version requirement (no longer pins to a specific
version), as no more breaking changes are to be expected after a release
candidate.
> Upgrade to latest RTIC release candidate
