src/lib.rs

Add prelude

---

src/gpio.rs
src/lib.rs
src/swm.rs
src/usart.rs

I'm currently working on issue #2, improving the safety of the pin API. While doing so I ran into some issues that require some deeper thinking, and also more extensive changes to the SWM API than I anticipated.
Instead of putting all of this into one big pull request, I decided it is better to extract the good parts of my branch and get that merged now, as the other changes will likely require some more thought and experimentation before they are ready.

Lay groundwork for pin API improvements

---

Cargo.toml
src/sleep.rs
src/wkt.rs

Upgrade to crates.io versions of dependencies

---

src/lib.rs
src/usart.rs

Use upstream `serial::Write` trait

---

src/gpio.rs
src/lib.rs

Implement `embedded_hal::digital::OutputPin`

---

Cargo.toml
src/lib.rs
src/usart.rs

Some smaller commits that didn't warrant their own PR.

Small changes

---

Cargo.toml
src/gpio.rs
src/lib.rs
src/pmu.rs
src/sleep.rs
src/swm.rs
src/syscon.rs
src/usart.rs
src/wkt.rs

Update to latest versions of cortex-m and lpc82x

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.toml
README.md
src/lib.rs

Release version 0.1.0

---

.cargo/config
Cargo.toml
examples/blinker.rs
memory.x
scripts/flash.sh

Add infrastructure for examples

---

src/clock.rs
src/pmu.rs
src/syscon.rs
src/wkt.rs

Also includes some general clock state cleanup.

Fix states of `LowPowerClock` and `IrcDerivedClock`

---

src/gpio.rs
src/swm.rs
src/usart.rs

This is a partial implementation of #48. Movable functions have been updated, fixed functions still need to be done.

Improve code generation for movable functions

---

src/usart.rs

Expect USART RX/TX to be assigned when enabling it

---

Cargo.toml
examples/i2c_vl53l0x.rs
src/i2c.rs
src/lib.rs
src/syscon.rs
src/usart.rs

This isn't that generally useful yet. Please refer to the documented limitations.

Add basic I2C API

---

.travis.yml
scripts/build-examples.sh
scripts/build.sh

This script is used by Travis, but can also be called locally, if a full
build is required.

Add build script

---

.cargo/config

Remove use of nightly-only compiler flag.

Update Cargo configuration

---

examples/gpio.rs
examples/usart.rs

Update a lot of outdated comments, and make the examples friendlier to use with the LPCXpresso824-MAX development board.

Update GPIO and USART examples

---

README.md

@lpc-rs/all Please take a look at https://github.com/lpc-rs/lpc-pac/pull/34, which explains the reasoning behind this change and why I want to run it by you.

Update reference to Braun Robotics

---

Cargo.toml
examples/gpio.rs
examples/i2c_vl53l0x.rs
examples/pmu.rs
examples/usart.rs
src/lib.rs

I'm currently working on sorting out the LPC845 problems, and this is something I came across on the way.

Re-export dependencies

---

examples/gpio_delay.rs
src/delay.rs
src/lib.rs

@david-sawatzke This is my take on your delay implementation. Please let me know what you think!

Simplify `Delay` construction

---

examples/pmu.rs
src/delay.rs
src/dma.rs
src/gpio.rs
src/i2c.rs
src/lib.rs
src/pmu.rs
src/sleep.rs
src/swm.rs
src/syscon.rs
src/usart.rs
src/wkt.rs

Also contains another cleanup. Details in the commit messages.

Export PAC as `pac`

---

examples/gpio_sleep.rs
src/syscon.rs
src/wkt.rs

For our purposes, they're the same.
https://github.com/lpc-rs/lpc8xx-hal/pull/171#discussion_r338108537

Merge Irc & FRO to an IOSC (internal oscillator)

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

Sorry, but due to the RustFest workshop, I need to merge this without review/approval. I need the new version right about now :-)

Release version 0.6.0

---

Cargo.toml
examples/i2c_vl53l0x.rs
examples/pmu.rs
examples/usart.rs
src/dma.rs
src/lib.rs
src/reg_proxy.rs
src/swm.rs
src/syscon.rs
src/syscon/clocksource_82x.rs
src/syscon/clocksource_845.rs
src/syscon/frg.rs
src/usart.rs

TODO:
- Improve Documentation
- Investigate swm & maybe force the user to enable it on 845

[WIP] Usart implementation

---

.travis.yml
build.rs
examples/gpio_simple.rs
examples/gpio_sleep.rs
examples/i2c_vl53l0x.rs
examples/pmu.rs
scripts/build.sh
src/delay.rs
src/dma.rs
src/gpio.rs
src/i2c.rs
src/pmu.rs
src/reg_proxy.rs
src/sleep.rs
src/swm.rs
src/syscon.rs
src/usart.rs
src/wkt.rs
tests/compiletest.rs

TODO:
- Maybe integrate clippy?
- not sure if that's possible outside github actions
- Nightly & stable styles will (probably) diverge, what then?
As discussed here: https://github.com/lpc-rs/lpc8xx-hal/pull/175#pullrequestreview-338579975

Format for rustfmt

---

src/usart.rs

Pac was updated some time ago, so now it's available

Check usart stat.uverrunint for lpc845 as well

---

Cargo.toml
examples/gpio_input.rs
src/gpio.rs
src/swm.rs

Also adds an example, currently only for lpc845

Implement digital input

---

src/syscon/clocksource_82x.rs
src/usart.rs

I've been working on #127, but the `RegProxy` infrastructure for that got a little hairy. I decided to regroup and try again later, once I've had a chance to think about it some more. These are some cleanup commits that came out of that work, and I think they're already an improvement in themselves.

Clean up USART API

---

Cargo.toml
examples/i2c_eeprom.rs
examples/i2c_vl53l0x.rs
examples/pmu.rs
examples/usart.rs
src/i2c.rs
src/lib.rs
src/syscon.rs
src/syscon/clocksource_82x.rs
src/syscon/clocksource_845.rs
src/usart.rs

I2c port to lpc845
- This is completely untested
-  also didn't instantiate I2C{1-3} yet

Add i2c to lpc845

---

src/gpio.rs
src/pins.rs
src/swm.rs

I'm still working on pin/GPIO improvements. This seemed like a good self-contained PR to make, before I get into the more heavy-handed changes.

Clean up `pins` module

---

src/gpio.rs
src/lib.rs
src/swm.rs

Still not what I set out to do with the pin/GPIO API, but I keep finding things that can be improved on the way.
This PR is based on #217. I recommend reviewing/merging that one first.

Simplify `GPIO`/`SWM` constructors

---

examples/gpio_delay.rs
examples/gpio_input.rs
examples/gpio_simple.rs
examples/gpio_sleep.rs
examples/gpio_timer.rs
examples/rtfm.rs
src/gpio.rs
src/pins.rs

Dertails in the commits. This PR is based on #219. I recommend reviewing/merging that one first.

Provide control over initial GPIO output; some cleanups

---

src/gpio.rs

`GpioPin` wasn't `Send` before, since `Registers` contains
`UnsafeCell`s, which aren't `Send`. This prevented moving `GpioPin`
instances into an interrupt handler using RTFM.
I think we could just implement `Send` for `GpioPin` instead, and even
though I think that should be fine, I don't fully understand the
implications. I opted to just remove `Registers` as a field and
construct it on demand, which is similar to what we do for other
peripherals.

Make `GpioPin` `Send`

---

Cargo.toml
examples/pinint.rs
src/lib.rs
src/pinint.rs
src/pinint/gen.rs
src/pinint/interrupt.rs
src/pinint/peripheral.rs
src/pinint/traits.rs
src/syscon.rs

This pull request is based on #226. I recommend reviewing/merging that one first.

Add PININT API

---

examples/gpio_delay.rs
examples/gpio_input.rs
examples/gpio_simple.rs
examples/gpio_sleep.rs
examples/gpio_timer.rs
examples/rtfm.rs
src/gpio.rs

@david-sawatzke I know we've butted heads over similar issues in the past, but I believe this case is a bit different, for reasons laid out in the first commit. Please let me know what you think.

Add infallible GPIO API

---

Cargo.toml
examples/i2c_eeprom.rs
examples/i2c_master_slave.rs
examples/i2c_vl53l0x.rs
src/i2c.rs
src/i2c/error.rs
src/i2c/instances.rs
src/i2c/master.rs
src/i2c/peripheral.rs
src/i2c/slave.rs
src/lib.rs

This pull request is based on #252. I recommend reviewing/merging that one first.

Add support for I2C slave mode

---

src/usart.rs
src/usart/flags.rs
src/usart/peripheral.rs
src/usart/rx.rs
src/usart/tx.rs

This pull request is based on #266. I recommend reviewing/merging that one first.

Add methods to query flags and enable/disable interrupts for USART

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

My current round of improvements is done (except for bug fixes and minor improvements, as required). I think it's time for the next release!
The following still needs to be done, before this can be merged:
- @david-sawatzke:
- @hannobraun:

Release version 0.8.0

---

Cargo.toml
scripts/build.sh
tests/compile-fail/swm/assign-function-to-multiple-pins.rs
tests/compile-fail/swm/assign-function-to-multiple-pins.stderr
tests/compile-fail/swm/assign-multiple-output-functions.rs
tests/compile-fail/swm/assign-multiple-output-functions.stderr
tests/compile-fail/swm/unassign-function-from-wrong-pin.rs
tests/compile-fail/swm/unassign-function-from-wrong-pin.stderr
tests/compile-fail/swm/unassign-unassigned-input-function.rs
tests/compile-fail/swm/unassign-unassigned-input-function.stderr
tests/compile-fail/swm/unassign-unassigned-output-function.rs
tests/compile-fail/swm/unassign-unassigned-output-function.stderr
tests/compiletest.rs

I hoped this would be quick and easy, but I ran into some hurdles (see https://github.com/dtolnay/trybuild/pull/59 and https://github.com/dtolnay/trybuild/issues/61). I figured I might just as well submit my in-progress work as a draft. I hope I can pick this back up later, but if anyone else wants to, feel free.

Re-enable compile-fail tests using trybuild

---

examples/usart.rs
src/reg_proxy.rs
src/syscon.rs
src/usart/clock.rs
src/usart/state.rs

These are the unrelated commits from #285. My work on #284 is sidelined for the moment, due to other priorities. I think it's better to merge these commits now, instead of waiting until I can finish #285.

Minor improvements

---

src/mrt.rs

this PR responds to comments from https://github.com/lpc-rs/lpc8xx-hal/pull/299

mrt: small `Ticks` conversion improvements 

---

examples/usart.rs
src/usart/clock.rs
src/usart/peripheral.rs
src/usart/rx.rs

See #284 for details. Also contains some random improvements that I made while working on this issue. I hope I'll be able to find a fix next week. If this drags on any longer, I'll submit those improvements separately.

Fix USART baud rate calculation

---

CHANGELOG.md
Cargo.toml
README.md
src/lib.rs

I think it's time for another release! Lots has happened since the last one.
The following still needs to be done:
- @david-sawatzke:
- @hannobraun:

Release version 0.9.0

---

Cargo.toml

This required no changes. I tested the RTIC example and it runs fine.

Upgrade to latest RTIC alpha

---

Cargo.toml
tests/compile-fail/swm/assign-function-to-multiple-pins.stderr
tests/compile-fail/swm/assign-multiple-output-functions.stderr
tests/compile-fail/swm/unassign-function-from-wrong-pin.stderr

Update dependency on embedded-time

---

.github/CODEOWNERS

This should automate review requests as per the comment.

Set `lpc8xx` team as owner of this repository

---

scripts/build.sh

This came out of my efforts to track down #324, but seems more broadly useful.

Improve build script output

---

scripts/build.sh
tests/compile-fail/swm/assign-multiple-output-functions.stderr

Also includes a small improvement to the build script.

Update error message for Trybuild

---

Cargo.toml
src/delay.rs

Includes the commits from #332, to make the CI build work.

Upgrade to latest embedded-hal alpha version
